In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import datasets
import seaborn as sns
import matplotlib.pyplot as plt

In [27]:
df=pd.read_csv('/home/loki/Developer/Ml/Project/LinearRegression/car_data.csv')

In [28]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [29]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [30]:
df.fuel.value_counts()

fuel
Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: count, dtype: int64

In [31]:
df.replace({'fuel':{'Petrol':0,'Diesel':1,'CNG':2,'LPG':3,'Electric':4}},inplace=True)

/tmp/ipykernel_18688/1991431406.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'fuel':{'Petrol':0,'Diesel':1,'CNG':2,'LPG':3,'Electric':4}},inplace=True)

In [33]:
df.sample(20)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
772,Volkswagen Polo 1.5 TDI Trendline,2011,220000,63657,1,Dealer,Manual,First Owner
4001,Maruti Celerio Green VXI,2017,365000,78000,2,Individual,Manual,First Owner
2268,Hyundai i10 Magna,2012,229999,49824,0,Dealer,Manual,First Owner
1935,Mahindra KUV 100 G80 K2,2018,320000,30000,0,Individual,Manual,Second Owner
4159,Tata Indigo LX,2012,125000,120000,1,Individual,Manual,First Owner
3000,Hyundai i20 Sportz Petrol,2010,250000,40000,0,Individual,Manual,First Owner
2232,Maruti Alto LX BSIII,2008,85000,120000,0,Individual,Manual,Second Owner
1970,Mahindra Bolero DI,2004,315000,110000,1,Individual,Manual,Third Owner
4236,Hyundai Grand i10 1.2 CRDi Asta,2018,465000,25000,1,Individual,Manual,First Owner
583,Maruti S-Cross Zeta DDiS 200 SH,2015,750000,45974,1,Trustmark Dealer,Manual,First Owner
3954,Mahindra TUV 300 T8,2016,700000,40000,1,Individual,Manual,First Owner
1402,Mahindra Scorpio SLE BSIII,2010,400000,185000,1,Individual,Manual,First Owner
1868,Hyundai i20 Asta 1.4 CRDi,2015,530000,77000,1,Individual,Manual,Second Owner
2352,Skoda Fabia 1.2L Diesel Ambiente,2010,260000,150000,1,Individual,Manual,First Owner
4251,Renault Duster 85PS Diesel RxE,2013,425000,170000,1,Dealer,Manual,First Owner
166,Tata Indigo CR4,2011,150000,155500,1,Individual,Manual,First Owner
4124,Hyundai i10 Magna,2012,240000,40000,0,Dealer,Manual,First Owner
348,Chevrolet Beat Diesel PS,2012,159000,68000,1,Dealer,Manual,First Owner
1005,Hyundai Verna CRDi 1.6 SX,2017,900000,50000,1,Individual,Manual,First Owner
4216,Toyota Innova 2.5 VX (Diesel) 8 Seater,2014,1050000,70000,1,Individual,Manual,First Owner

In [34]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,0,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,0,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,1,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,0,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,1,Individual,Manual,Second Owner

In [35]:
df.seller_type.value_counts()

seller_type
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: count, dtype: int64

In [37]:
df.replace({'seller_type':{'Individual':0,'Dealer':1,'Trustmark Dealer':2}},inplace=True)

/tmp/ipykernel_18688/321664593.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'seller_type':{'Individual':0,'Dealer':1,'Trustmark Dealer':2}},inplace=True)

In [38]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,0,0,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,0,0,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,1,0,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,0,0,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,1,0,Manual,Second Owner

In [41]:
df.transmission.value_counts()

transmission
Manual       3892
Automatic     448
Name: count, dtype: int64

In [43]:
df.replace({'transmission':{'Manual':0,'Automatic':1}},inplace=True)

/tmp/ipykernel_18688/3436730578.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'transmission':{'Manual':0,'Automatic':1}},inplace=True)

In [45]:
df.owner.value_counts()

owner
First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: count, dtype: int64

In [46]:
df.replace({'owner':{'First Owner':0,'Second Owner':1,'Third Owner':2,'Fourth & Above Owner':2,'Test Drive Car':3}},inplace=True)

/tmp/ipykernel_18688/198556119.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'owner':{'First Owner':0,'Second Owner':1,'Third Owner':2,'Fourth & Above Owner':2,'Test Drive Car':3}},inplace=True)

In [47]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,0,0,0,0
1,Maruti Wagon R LXI Minor,2007,135000,50000,0,0,0,0
2,Hyundai Verna 1.6 SX,2012,600000,100000,1,0,0,0
3,Datsun RediGO T Option,2017,250000,46000,0,0,0,0
4,Honda Amaze VX i-DTEC,2014,450000,141000,1,0,0,1
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,1,0,0,1
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,1,0,0,1
4337,Maruti 800 AC BSIII,2009,110000,83000,0,0,0,1
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,1,0,0,0
4339,Renault KWID RXT,2016,225000,40000,0,0,0,0

In [52]:
Y=df.selling_price
X=df.drop(['name','selling_price'],axis=1)

In [53]:
model=LinearRegression()

In [54]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [55]:
model.fit(X_train,Y_train)

LinearRegression()

In [63]:
X_train_predict=model.predict(X_train)
from sklearn.metrics import mean_absolute_error
mab_train=mean_absolute_error(Y_train,X_train_predict)
mab_train

234597.98347966137